server:
  port: 8085

database:
  engine: SQLite
  url: jdbc:sqlite:db/landlords.sqlite3
  username:
  password:

redis:
  host: 127.0.0.1
  port: 6379

landlords:
  frontend-host: landlords.pushyzheng.com
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad
  max-seconds-for-every-round: 30
