server:
  port: 18080

database:
  engine: SQLite
  url: jdbc:sqlite:db/landlords-test.sqlite3
  username:
  password:

redis:
  host: 127.0.0.1
  port: 6379

landlords:
  frontend-host: localhost:9000
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad

logging:
  level:
    site.pushy.landlords.dao: debug
