version: '3'

services:
  web:
    build: web
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    build: mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=landlords